
# 核心任务

- name: guacamole
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common , tags: "role_common" }
    - { role: role_cloud, tags: "role_cloud" }
    - { role: docker, tags: "docker" }
    - { role: role_nginx, tags: "role_nginx" }
    - { role: guacamole, tags: "guacamole" }
    - { role: role_preend, tags: "preend" }
    - { role: role_end , tags: "role_end" } 

  

    


                                                                                                    