---
- name: docker pull images
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - mysql:5.7
    - guacamole/guacd
    - guacamole/guacamole

- name: Create guacd container
  docker_container:
    name: guacd
    image: guacamole/guacd
    ports:
      - "4822:4822"
    state: started
    restart: yes
    restart_policy: always

- name: Create mysql date dirctory
  file: 
    path: /data/mysql
    state: directory

- name: Create mysql container
  docker_container:
    name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: "{{mysql_password}}"
    state: started
    restart: yes
    restart_policy: always

- name: Createa guacamole container
  docker_container:
    name: guacamole
    image: guacamole/guacamole
    ports:
      - "8080:8080"
    links:
      - mysql:mysql
      - guacd:guacd
    env:
      MYSQL_USER: "{{mysql_user}}"
      MYSQL_PASSWORD: "{{mysql_password}}"
      MYSQL_DATABASE: "guacamole"
    state: started
    restart: yes
    restart_policy: always

- name: generate initdb.sql
  shell: docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --mysql > initdb.sql
  args:
    chdir: ~/

- name: initializ mysql -1 get docker0's gateway
  shell: ip a | grep 'docker0' | awk -F 'link/ether' 'NR==2{print $1}' | awk -F '/' '{print $1}' | awk -F ' ' '{print $2}'
  register: docker0_gateway

- name: initializ mysql -2 install mysql-client-core-5.7
  apt: name=mysql-client-core-5.7  state=latest

- name: initializ mysql -3 create guacamole database
  mysql_db:
    name: guacamole
    login_user: "{{mysql_user}}"
    login_password: "{{mysql_password}}"
    login_host: "{{docker0_gateway.stdout}}"
    state: present

- name: initializ mysql -4 import guacamole tables
  mysql_db:
    name: guacamole
    login_user: "{{mysql_user}}"
    login_password: "{{mysql_password}}"
    login_host: "{{docker0_gateway.stdout}}"
    state: import
    target: ~/initdb.sql

- name: delete initdb.sql
  file:
    path: ~/initdb.sql
    state: absent
    
# TODO: 设置nginx端口转发
- name: copy nginx configuration file 
  copy: 
    src: default
    dest: /etc/nginx/conf.d/default.conf

- name: restart nginx
  service: name=nginx  state=restarted